[build]
  base = ""
  command = "cd server && npm install && cd ../client && npm install --save --legacy-peer-deps && npm run build"
  publish = "client/"

[[redirects]]
  from = "/*"
  to = "/client/public/index.html"
  status = 200