[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "src/"
[build]
  base = "server/"
  command = "npm install"
  functions = "src/"
[[redirects]]
  to = "/.netlify/functions/api/:splat"
  from = "/*"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"