[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "server/src/"
[build]
  base = "server/"
  functions = "src/"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"