[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  functions = 'server/src/'
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "server/src/index/:splat"
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"