[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  base = "server/"
  functions = "src/"
[[redirects]]
  force = true
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"