[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/src/index/:splat"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"