#------------------------
# GitHub Actions
#------------------------

name: GitHub-Actions-Tests
env:
  APP_NAME: "Cryptocurrency Info"
  DEPLOY_PACKAGE_NAME: "deploy-ver-${{ github.sha }}"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  client_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '14'
    - name: Run tests on client
      run : |
        sudo rm -rf node_modules package-lock.json && npm install
        npm run test
  server_tests: 
    runs-on: ubuntu-latest
    needs: [client_tests]
    defaults:
      run:
        working-directory: ./server
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '14'
    - name: Run tests on server
      run : |
        sudo rm -rf node_modules package-lock.json && npm install
        npm run test
  cypress_tests:
    runs-on: ubuntu-22.04
    needs: [server_tests]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '14'
    - name: Run server
      run : |
        cd server
        sudo rm -rf node_modules package-lock.json && npm install
        npm start &
        sleep 10 &&
        curl http://localhost:4000
    - name: Run client
      run : |
        cd client
        sudo rm -rf node_modules package-lock.json && npm install
        npm start &
        sleep 10 &&
        curl http://localhost:3000
    - name: Run Cypress
      uses: cypress-io/github-action@v6
      with:
        browser: edge
        working-directory: ./client
