#------------------------
# GitHub Actions
#------------------------

name: GitHub-Actions-Tests
env:
  APP_NAME: "Cryptocurrency Info"
  DEPLOY_PACKAGE_NAME: "deploy-ver-${{ github.sha }}"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  client_tests:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./client
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Run tests on client
      run : |
        npm install --save --legacy-peer-deps
        npm run test
  server_tests: 
    runs-on: windows-latest
    needs: [client_tests]
    defaults:
      run:
        working-directory: ./server
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Run tests on server
      run : |
        npm install --save --legacy-peer-deps
        npm run test
  cypress_tests:
    runs-on: windows-latest
    needs: [server_tests]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Run server
      shell: bash
      run : |
        cd server
        npm install --save --legacy-peer-deps
        npm start &
        sleep 10 &&
        curl http://localhost:4000
    - name: Run client
      shell: bash
      run : |
        cd client
        npm install --save --legacy-peer-deps
        npm start &
        sleep 10 &&
        curl http://localhost:3000
    - name: Run Cypress
      shell: bash
      run : |
        cd client
        npx cypress run --browser edge
    - name: Uploads artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-snapshots
        path: ./client/cypress/snapshots
        browser: 
